### ISSUE TITLE
Support HTTP Digest authentication

### ISSUE THREAD

**Issue by maikk** [mattrajca/DAVKit#2]
Many WebDAV servers use HTTP Digest authentication over HTTP Basic authentication for security reasons. The WebDAV spec itself even makes Digest authentication mandatory (at least when using insecure connections): http://www.webdav.org/specs/rfc4918.html#rfc.section.20.1

Would be great to see this implemented.
Thanks for the cool framework anyway – works like a charm (with HTTP Basic authentication).

  -- Michael

**Comment by mattrajca** [comment]
will do this weekend. I initially develop these frameworks for internal use so let me know if there is any other way I could make it more generic and reusable.

**Comment by maikk** [comment]
Nah, don't bother, I went down the wrong road. HTTP Digest authentication should be supported already. From the Apple Docs:

> #### HTTP Digest Authentication (NSURLAuthenticationMethodHTTPDigest)
> 
> Like basic authentication, digest authentication just requires a user name and password (the digest is generated automatically). Prompt the user for the necessary information and create an NSURLCredential object with <pre>credentialWithUser:password:persistence:</pre>

Found something else though (which was my problem in the first place). Will open a separate issue for that and close this one.
