### ISSUE TITLE
Don't use hardcoded XML namespace prefixes

### ISSUE THREAD

**Issue by maikk** [mattrajca/DAVKit#3]
In DAVListingParser.m attribute names are compared including their namespace prefix:

```
if ([elementName isEqualToString:@"D:href"]) {...}
```

That is bound to fail in some cases since the namespace prefix is variable and can be set to the creator's liking.

I'll create a patch implementing

```
- (void)parser:(NSXMLParser *)parser didStartMappingPrefix:(NSString *)prefix toURI:(NSString *)namespaceURI
```

and will provide it here.

  -- Michael

**Comment by maikk** [comment]
Ok, that was easier than I tought. I just added

```
[_parser setShouldProcessNamespaces:YES];
```

to switch on the processing of XML namespaces in the NSXMLParser instance and then removed the namespace prefix from all attribute name comparisons. Et voilá, it now works against the client's WebDAV server. Cool.

I'll leave this issue open for you to close it if you want to integrate my changes into your code.

Thanks again for the great framework.
  -- Michael

Here's the full patch:

<pre>
Index: /.../Core/DAVListingParser.m
===================================================================
--- /.../Core/DAVListingParser.m    (revision 79)
+++ /.../Core/DAVListingParser.m    (working copy)
@@ -28,6 +28,7 @@
        
        _parser = [[NSXMLParser alloc] initWithData:data];
        [_parser setDelegate:self];
+      [_parser setShouldProcessNamespaces:YES];
    }
    return self;
 }
@@ -54,7 +55,7 @@
    
    _currentString = [[NSMutableString alloc] init];
    
-   if ([elementName isEqualToString:@"D:response"]) {
+   if ([elementName isEqualToString:@"response"]) {
        _currentItem = [[DAVResponseItem alloc] init];
    }
 }
@@ -71,22 +72,22 @@
 - (void)parser:(NSXMLParser *)parser didEndElement:(NSString *)elementName 
   namespaceURI:(NSString *)namespaceURI qualifiedName:(NSString *)qName {
     
-   if ([elementName isEqualToString:@"D:href"]) {
+   if ([elementName isEqualToString:@"href"]) {
        _currentItem.href = _currentString;
    }
-   else if ([elementName isEqualToString:@"D:getcontentlength"]) {
+   else if ([elementName isEqualToString:@"getcontentlength"]) {
        _currentItem.contentLength = [_currentString integerValue];
    }
-   else if ([elementName isEqualToString:@"D:getcontenttype"]) {
+   else if ([elementName isEqualToString:@"getcontenttype"]) {
        _currentItem.contentType = _currentString;
    }
-   else if ([elementName isEqualToString:@"D:modificationdate"]) {
+   else if ([elementName isEqualToString:@"modificationdate"]) {
        _currentItem.modificationDate = [self _ISO8601DateWithString:_currentString];
    }
-   else if ([elementName isEqualToString:@"D:creationdate"]) {
+   else if ([elementName isEqualToString:@"creationdate"]) {
        _currentItem.creationDate = [self _ISO8601DateWithString:_currentString];
    }
-   else if ([elementName isEqualToString:@"D:response"]) {
+   else if ([elementName isEqualToString:@"response"]) {
        [_items addObject:_currentItem];
        
        [_currentItem release];
</pre>

**Comment by mattrajca** [comment]
Thanks!
