### ISSUE TITLE
Memory leak in DAVListingParser

### ISSUE THREAD

**Issue by autresphere** [mattrajca/DAVKit#4]
Hi there,

It seems [DAVListingParser parser: didStartElement: namespaceURI: qualifiedName: attributes:] generates a memory leak on _currentString in some cases. The leak happens when _currentString is not nil at the beginning of this method (in this case, it is always "\n", not sure where it comes from).

Adding 
[currentString release];
just before 
currentString = [[NSMutableString alloc] init];
does the trick.

By the way, keep up the good work!

**Comment by mattrajca** [comment]
Thanks! Fixed!
