### ISSUE TITLE
contentLength incorrect for files bigger than 2GB

### ISSUE THREAD

**Issue by sylverb** [mattrajca/DAVKit#6]
some NSInteger have to be changed to "long long" :
in DAVListingParser.m :
else if ([elementName isEqualToString:@"getcontentlength"]) {
-   _currentItem.contentLength = [_currentString intValue];
-   _currentItem.contentLength = [_currentString longLongValue];
  }

DAVResponseItem.h :
-   NSInteger contentLength;
-   long long contentLength;

-@property (assign) NSInteger contentLength;
+@property (assign) long long contentLength;

DAVResponseItem.m :
-   return [NSString stringWithFormat:@"href = %@; modificationDate = %@; contentLength = %d; "
  +- (NSString *)description {
  return [NSString stringWithFormat:@"href = %@; modificationDate = %@; contentLength = %lld; "

**Comment by mattrajca** [comment]
Fixed in commit 86c769e12b7ff048e420
